site_name: SignalBlocks
site_description: "A Python library for visualizing and manipulating signal processing signals & systems"
site_author: "Miguel Á. Martín-Fernández"
repo_url: https://github.com/miguelmartfern/SignalBlocks
repo_name: miguelmartfern/SignalBlocks

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["signalblocks"]  # Directory where your .py modules are located

nav:
  - Home: index.md
  - Reference:
      - API Documentation: reference.md